### ISSUE TITLE
Add environment variable to set "--use-proxy" behavior

### ISSUE THREAD

**Issue by diranged** [kubecost/kubectl-cost#107] opened 2022-06-10 03:23 UTC
For users who want to use the Kubernetes API Proxy method for the `kubectl cost` command, it would be nice to be able to set an environment variable to configure the behavior of the `--use-proxy` flag.

gz#1949<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1949'>Zendesk ticket #1949</a>)</i>

**Comment by AjayTripathy** [comment] 2022-06-10 07:00
@dramich did you end up doing something here previously for the core cost-model stuff?

**Comment by dramich** [comment] 2022-06-10 15:59
This is related to the kubectl plugin not using envvars

**Comment by dwbrown2** [comment] 2022-06-13 18:29
cc @michaelmdresser who I believe explored different ways to proxy when we first created this project

**Comment by michaelmdresser** [comment] 2022-06-13 20:49
Just to summarize the expected behavior so everyone understands what's going on (I talked with @srpomeroy about this): instead of having to do this:

```sh
kubectl cost --use-proxy ...foo
kubectl cost --use-proxy ...bar
```

We want to expose functionality like this:
```sh
export KUBECTL_COST_USE_PROXY=true
kubectl cost ...foo
kubectl cost ...bar
```

Essentially, we want to make a roughly-equivalent set of env vars that can be used in place of flags. At a minimum, this issue is a request for just the behavior shown in the above examples.

**Comment by michaelmdresser** [comment] 2022-06-27 16:22
I recommend using https://github.com/spf13/viper for this because we use it elsewhere -- see existing usage in OpenCost:
https://github.com/kubecost/opencost/blob/97c57edf2f80b094c54a02ee081952eea8f16b27/pkg/cmd/commands.go#L60-L89

**Comment by avrodrigues5** [comment] 2022-07-11 16:39
Hello, You could use the environment variable KUBECTL_COST_USE_PROXY to set --use-proxy behavior from release [v0.2.11](https://github.com/kubecost/kubectl-cost/releases/tag/v0.2.11). Closing this issue.

**Closed by avrodrigues5** 2022-07-11 16:39 UTC
Labels: enhancement, good first issue
